infrastructure:
  DB:
    USERNAME: appointment_service_user
    PASSWORD: appointment_service_user

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_user_service_db
    username: ${infrastructure.DB.USERNAME}
    password: ${infrastructure.DB.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
      - localhost:9097
    producer:
      acks: -1
      batch-size: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: zstd

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html
    operations-sorter: method
    doc-expansion: none
app:
  jwt:
    expiration-ms: 7200000 # 2 hours
    secret: "8adLFE4RHIqYOXhB7ZLjgqdRJWAioTMzlblC8XyKrc8="
  kafka:
    notification-topic: appointment-system-notifications
  client-url: http://localhost:4200
  verification-token:
    expiration-ms: 86400000 # 24 hours
  encryption-key: "AHaeXmeTddI9EsmAOiK2l8diUFH5htXacTEP4wa5zBs="
  open-api:
    info:
      title: Appointment Auth Service
      description: Appointment Authentication Service
      version: 1.0.0
  cors:
    allowed-origins:
      - http://localhost:9000
    allowed-methods:
      - POST
      - GET
      - PUT
      - OPTIONS
      - DELETE
      - PATCH
    allowed-headers:
      - "*"
    max-age: 3600
  white-list:
    - "/api/v1/account/**"
    - "/v3/api-docs/**"
    - "/auth/swagger-ui.html/**"
    - "/auth/v3/api-docs/**"

server:
  port: 9001
